# Autogenerated wrapper script for FireFly_jll for aarch64-apple-darwin-mpi+mpich
export libfirefly

using FLINT_jll
using GMP_jll
using Zlib_jll
using jemalloc_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("FireFly")
JLLWrappers.@declare_library_product(libfirefly, "@rpath/libfirefly.dylib")
function __init__()
    JLLWrappers.@generate_init_header(FLINT_jll, GMP_jll, Zlib_jll, jemalloc_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libfirefly,
        "lib/libfirefly.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
